<a href="https://colab.research.google.com/github/sarvagna23/AI-Amrita/blob/main/Numpy's/Numpy's.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Dictionaries**

*A dictionary stores a key value pairs*


In [ ]:
d={'a':'ant','b':'ball'} #creates dictionary with the key and values
print(d['a'])   #prints value of key 'a' in dictionary d
print('a' in d)  # checks wethet there is 'a' in dictionary d and returns boolean

ant
True


In [ ]:
d['c']='cat'  #a new entry in the dictionary
print(d['c']) #printing the value of key 'c'

cat


In [ ]:
print(d.get('c','N/A'))  # tho it is N/A given but it prints default as cat
del d['c']  # now the value has been deleted
print(d.get('c','N/A')) # now it prints N/A

cat
N/A


In [ ]:
print(d)

{'a': 'ant', 'b': 'ball'}


In [ ]:
c=dict(a='ant',b='ball',c='cat')
for alphabets, words in c.items():
  print('{} for {}'.format(alphabets,words))

a for ant
b for ball
c for cat


In [ ]:
num=[0,1,2,3,4]
even_num_to_square = {x: x ** 2 for x in num if x % 2 == 0}
print(even_num_to_square)


{0: 0, 2: 4, 4: 16}


In [ ]:
num=[0,1,2,3,4]
for x in num:
  even_num={x:x**2}
even_num

{4: 16}

In [ ]:
a_dict = {'one': 1, 'two': 2, 'thee': 3, 'four': 4}
new_dict = {}
for key, value in a_dict.items():
  new_dict[value] = key
new_dict

{1: 'one', 2: 'two', 3: 'thee', 4: 'four'}

**Numpy's**

To use numpys we first need to import numpys as np

In [ ]:
import numpy as np

The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [ ]:
a=np.array([1,2,3])
print(a.shape,a.size,a[1])

(3,) 3 2


In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

# Get a specific element [r, c]
a[1, 5]
#a[1,-2] will give you the same element 13.

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


13

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


**Array Indexing**
Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])# now to get an element from 2nd and 3rd rows and columns 3rd and 4th
print(a)
b=a[1:,2:]
print(b)
c=a[1:,1:3]
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]


In [ ]:
print(a[1, 1])
c[0, 0] = 77    # c[0, 0] is the same piece of data as a[0, 1]
 #modifying b also chages the original data

6


In [ ]:
print(a[1,1])

77


In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [5]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


In [7]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))
print(x - y)
print(np.subtract(x, y))
print(np.multiply(x,y))
print(x / y)
print(np.divide(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


unlike MATLAB, * is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects

In [9]:
v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))
print(v@w)

219
219
219


can also use the @ operator which is equivalent to numpy's dot operator.

In [11]:
x = np.array([[1,2],[3,4]])  
y = np.array([[5,6],[7,8]])
print(x.dot(y))  #rank 2 array
print(x.dot(v))  #rank 1 array

[[19 22]
 [43 50]]
[29 67]


In [12]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [13]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv) 

[[ 9 10]
 [ 9 10]
 [ 9 10]
 [ 9 10]]


In [14]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [17]:
x = np.array([[1,2,3], [4,5,6]])
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)
#another method is to reshape
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]


In [18]:
print(x * 2) #multiplying with constant

[[ 2  4  6]
 [ 8 10 12]]
